<a href="https://colab.research.google.com/github/subham-28/PyTorch/blob/main/tensors_in_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
print(torch.__version__)

2.10.0+cu128


In [2]:
if torch.cuda.is_available():
  print("GPU is available")
  print(torch.cuda.get_device_name(0))
  print(torch.cuda.device_count())
else:
  print("GPU is not available")

GPU is available
Tesla T4
1


## Creating Tensor

In [3]:
#using empty
a=torch.empty(2,3)
a

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [4]:
#check type
type(a)

torch.Tensor

In [5]:
#using zeroes
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [6]:
#using one
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [7]:
#using rand
torch.rand(2,3)

tensor([[0.3320, 0.7143, 0.5108],
        [0.4410, 0.7041, 0.7561]])

In [8]:
torch.rand(2,3)

tensor([[0.7344, 0.6001, 0.7312],
        [0.3119, 0.3009, 0.4202]])

In [9]:
# manual seed (everytime the rand generates the same output)'
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [10]:
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [11]:
#using tensor
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [12]:
#using range
torch.arange(1,10,2) #left,right,jump

tensor([1, 3, 5, 7, 9])

In [13]:
#using linspace
torch.linspace(0,10,10)

tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])

In [14]:
#using eye
torch.eye(5)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [15]:
#using full
torch.full((3,3),5)

tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])

## Tensor shape

In [16]:
x=torch.tensor([[1,2,3],[4,5,6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [17]:
x.shape

torch.Size([2, 3])

In [18]:
torch.empty_like(x) #shape copied

tensor([[0, 0, 0],
        [0, 0, 0]])

In [19]:
torch.zeros_like(x) #shape copied

tensor([[0, 0, 0],
        [0, 0, 0]])

In [20]:
torch.ones_like(x) #shape copied

tensor([[1, 1, 1],
        [1, 1, 1]])

In [ ]:
torch.rand_like(x)  #error

## Tensor Datatype

In [22]:
x.dtype

torch.int64

In [23]:
#assign datatype
torch.tensor([1.0,2.0,3.0],dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [24]:
#assign datatype
torch.tensor([1,2,3],dtype=torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

In [25]:
x.to(torch.float64)

tensor([[1., 2., 3.],
        [4., 5., 6.]], dtype=torch.float64)

In [26]:
torch.rand_like(x,dtype=torch.float64)

tensor([[0.1015, 0.6642, 0.9736],
        [0.6941, 0.3464, 0.9751]], dtype=torch.float64)

## Mathematical Operations

### 1. Scalar Operation

In [27]:
x=torch.rand(2,2)
x

tensor([[0.2239, 0.3023],
        [0.1784, 0.8238]])

In [28]:
#addition
x+2

tensor([[2.2239, 2.3023],
        [2.1784, 2.8238]])

In [29]:
#substraction
x-2

tensor([[-1.7761, -1.6977],
        [-1.8216, -1.1762]])

In [30]:
#multiplication
x*2

tensor([[0.4478, 0.6047],
        [0.3568, 1.6477]])

In [31]:
#division
x/2

tensor([[0.1119, 0.1512],
        [0.0892, 0.4119]])

In [32]:
#mod
x%2

tensor([[0.2239, 0.3023],
        [0.1784, 0.8238]])

In [33]:
#power
x**2

tensor([[0.0501, 0.0914],
        [0.0318, 0.6787]])

### 2. Element wise operation

In [34]:
a = torch.rand(2,3)
b = torch.rand(2,3)
a,b

(tensor([[0.5557, 0.9770, 0.4440],
         [0.9478, 0.7445, 0.4892]]),
 tensor([[0.2426, 0.7003, 0.5277],
         [0.2472, 0.7909, 0.4235]]))

In [35]:
#add
a+b

tensor([[0.7983, 1.6774, 0.9717],
        [1.1950, 1.5354, 0.9127]])

In [36]:
#sub
a-b

tensor([[ 0.3132,  0.2767, -0.0837],
        [ 0.7007, -0.0464,  0.0657]])

In [37]:
#mul
a*b

tensor([[0.1348, 0.6842, 0.2343],
        [0.2343, 0.5888, 0.2072]])

In [38]:
#div
a/b

tensor([[2.2912, 1.3951, 0.8415],
        [3.8346, 0.9413, 1.1552]])

In [39]:
#power
a**b

tensor([[0.8672, 0.9839, 0.6515],
        [0.9868, 0.7919, 0.7388]])

In [40]:
#abs
c=torch.tensor([-1,-2,-3,-4])
torch.abs(c)

tensor([1, 2, 3, 4])

In [41]:
#negative
torch.neg(c)

tensor([1, 2, 3, 4])

In [42]:
#round
d=torch.tensor([1.9,2.3,3.7,4.4])
torch.round(d)

tensor([2., 2., 4., 4.])

In [43]:
#ceil
d=torch.tensor([1.9,2.3,3.7,4.4])
torch.ceil(d)

tensor([2., 3., 4., 5.])

In [44]:
#floor
d=torch.tensor([1.9,2.3,3.7,4.4])
torch.floor(d)

tensor([1., 2., 3., 4.])

In [45]:
#clamp
d=torch.tensor([1.9,2.3,3.7,4.4])
torch.clamp(d,min=2,max=3)

tensor([2.0000, 2.3000, 3.0000, 3.0000])

## Reduction Operation

In [46]:
e=torch.randint(size=(2,3),low=0,high=10,dtype=torch.float32)
e

tensor([[5., 7., 3.],
        [9., 4., 0.]])

In [47]:
#sum
torch.sum(e)

tensor(28.)

In [48]:
#sum of cols
torch.sum(e,dim=0)

tensor([14., 11.,  3.])

In [49]:
#sum of rows
torch.sum(e,dim=1)

tensor([15., 13.])

In [50]:
torch.mean(e,dim=0)

tensor([7.0000, 5.5000, 1.5000])

In [51]:
torch.median(e)

tensor(4.)

In [52]:
torch.max(e)
torch.min(e)

tensor(0.)

In [53]:
torch.prod(e)

tensor(0.)

In [54]:
torch.std(e)

tensor(3.1411)

In [55]:
torch.var(e)

tensor(9.8667)

In [56]:
#argmax : gives the pos of the largest element
torch.argmax(e)

tensor(3)

In [57]:
#argmin
torch.argmin(e)

tensor(5)

## Matrix Operation

In [58]:
f=torch.randint(size=(2,3),low=0,high=10)
g=torch.randint(size=(3,2),low=0,high=10)
f,g

(tensor([[5, 7, 5],
         [9, 9, 7]]),
 tensor([[5, 9],
         [8, 9],
         [7, 9]]))

In [59]:
#matrix mul
torch.matmul(f,g)

tensor([[116, 153],
        [166, 225]])

In [60]:
vector1=torch.tensor([1,2])
vector2=torch.tensor([3,4])

In [61]:
#dot prod
torch.dot(vector1,vector2)

tensor(11)

In [62]:
torch.transpose(f,0,1)

tensor([[5, 9],
        [7, 9],
        [5, 7]])

In [63]:
torch.det(torch.matmul(f,g).float())

tensor(702.0005)

In [64]:
torch.inverse(torch.matmul(f,g).float())

tensor([[ 0.3205, -0.2179],
        [-0.2365,  0.1652]])

## Comparison Operation

In [65]:
i=torch.randint(size=(2,3),low=0,high=10)
j=torch.randint(size=(2,3),low=0,high=10)
i,j

(tensor([[2, 6, 7],
         [7, 8, 3]]),
 tensor([[6, 1, 5],
         [5, 0, 4]]))

In [66]:
i>j

tensor([[False,  True,  True],
        [ True,  True, False]])

In [67]:
i<j

tensor([[ True, False, False],
        [False, False,  True]])

In [68]:
i==j

tensor([[False, False, False],
        [False, False, False]])

In [69]:
i!=j

tensor([[True, True, True],
        [True, True, True]])

## Special func

In [70]:
k=torch.randint(size=(2,3),low=0,high=10,dtype=torch.float32)
k

tensor([[3., 8., 8.],
        [3., 3., 5.]])

In [71]:
#log
torch.log(k)

tensor([[1.0986, 2.0794, 2.0794],
        [1.0986, 1.0986, 1.6094]])

In [72]:
torch.exp(k)

tensor([[  20.0855, 2980.9580, 2980.9580],
        [  20.0855,   20.0855,  148.4132]])

In [73]:
torch.sqrt(k)

tensor([[1.7321, 2.8284, 2.8284],
        [1.7321, 1.7321, 2.2361]])

In [74]:
torch.sigmoid(k)

tensor([[0.9526, 0.9997, 0.9997],
        [0.9526, 0.9526, 0.9933]])

In [75]:
torch.softmax(k,dim=0)

tensor([[0.5000, 0.9933, 0.9526],
        [0.5000, 0.0067, 0.0474]])

In [76]:
torch.relu(k)

tensor([[3., 8., 8.],
        [3., 3., 5.]])

## Inplace operations

In [77]:
m = torch.rand(2,3)
n = torch.rand(2,3)
m,n

(tensor([[0.9454, 0.7116, 0.1157],
         [0.6574, 0.3451, 0.0453]]),
 tensor([[0.9798, 0.5548, 0.6868],
         [0.4920, 0.0748, 0.9605]]))

In [78]:
m.add_(n) # no new tensor created

tensor([[1.9251, 1.2663, 0.8025],
        [1.1494, 0.4199, 1.0058]])

In [79]:
m

tensor([[1.9251, 1.2663, 0.8025],
        [1.1494, 0.4199, 1.0058]])

In [80]:
n

tensor([[0.9798, 0.5548, 0.6868],
        [0.4920, 0.0748, 0.9605]])

In [81]:
m.relu_()

tensor([[1.9251, 1.2663, 0.8025],
        [1.1494, 0.4199, 1.0058]])

## Copying a tensor

In [82]:
a = torch.rand(2,3)
a

tensor([[0.3271, 0.0103, 0.9516],
        [0.2855, 0.2324, 0.9141]])

In [83]:
b=a

In [84]:
a[0][0]=0 # both a and b are changed

In [85]:
a

tensor([[0.0000, 0.0103, 0.9516],
        [0.2855, 0.2324, 0.9141]])

In [86]:
b

tensor([[0.0000, 0.0103, 0.9516],
        [0.2855, 0.2324, 0.9141]])

In [87]:
id(a),id(b)

(137696612604720, 137696612604720)

In [88]:
b=a.clone()

In [89]:
id(a),id(b)

(137696612604720, 137696612021776)

In [90]:
a,b

(tensor([[0.0000, 0.0103, 0.9516],
         [0.2855, 0.2324, 0.9141]]),
 tensor([[0.0000, 0.0103, 0.9516],
         [0.2855, 0.2324, 0.9141]]))

## Tensor operation on GPU

In [91]:
torch.cuda.is_available()

True

In [92]:
device=torch.device('cuda')

In [93]:
#creating a new tensor on GPU
torch.rand((2,3),device=device)

tensor([[0.3563, 0.0303, 0.7088],
        [0.2009, 0.0224, 0.9896]], device='cuda:0')

In [96]:
#moving existing tensor to GPU
a_gpu=a.to(device)

In [97]:
a_gpu+5

tensor([[5.0000, 5.0103, 5.9516],
        [5.2855, 5.2324, 5.9141]], device='cuda:0')

In [99]:
import time

size=10000

matrix_cpu1=torch.randn(size,size)
matrix_cpu2=torch.randn(size,size)

start_time=time.time()
result_cpu=torch.matmul(matrix_cpu1,matrix_cpu2)
cpu_time = time.time()-start_time
print(f"cpu_time={cpu_time}")

matrix_gpu1=matrix_cpu1.to('cuda')
matrix_gpu2=matrix_cpu2.to('cuda')

start_time=time.time()
result_gpu=torch.matmul(matrix_gpu1,matrix_gpu2)
torch.cuda.synchronize()
gpu_time = time.time()-start_time
print(f"gpu_time={gpu_time}")

print("Speed Up: ", cpu_time/gpu_time)

cpu_time=16.173453092575073
gpu_time=0.7246496677398682
Speed Up:  22.318996078503627


## Reshaping Tensor

In [100]:
a

tensor([[0.0000, 0.0103, 0.9516],
        [0.2855, 0.2324, 0.9141]])

In [103]:
a.reshape(3,2)

tensor([[0.0000, 0.0103],
        [0.9516, 0.2855],
        [0.2324, 0.9141]])

In [104]:
a.flatten()

tensor([0.0000, 0.0103, 0.9516, 0.2855, 0.2324, 0.9141])

In [105]:
b=torch.rand(2,3,4)
b

tensor([[[0.6164, 0.1888, 0.0332, 0.6725],
         [0.2147, 0.8954, 0.0273, 0.6760],
         [0.8880, 0.2082, 0.1337, 0.6727]],

        [[0.1681, 0.0738, 0.1151, 0.0083],
         [0.0504, 0.1486, 0.8395, 0.8331],
         [0.4379, 0.4083, 0.5009, 0.4067]]])

In [106]:
#permute
b.permute(2,0,1)

tensor([[[0.6164, 0.2147, 0.8880],
         [0.1681, 0.0504, 0.4379]],

        [[0.1888, 0.8954, 0.2082],
         [0.0738, 0.1486, 0.4083]],

        [[0.0332, 0.0273, 0.1337],
         [0.1151, 0.8395, 0.5009]],

        [[0.6725, 0.6760, 0.6727],
         [0.0083, 0.8331, 0.4067]]])

In [108]:
b.permute(2,0,1).shape

torch.Size([4, 2, 3])

In [116]:
#unsqueeze
#img size
c=torch.rand(226,226,3)
c=c.unsqueeze(0)
c.unsqueeze(0).shape,c.unsqueeze(2).shape


(torch.Size([1, 1, 226, 226, 3]), torch.Size([1, 226, 1, 226, 3]))

In [118]:
# squeeze
c.squeeze(0).shape

torch.Size([226, 226, 3])

## NumPy and PyTorch

In [119]:
import numpy as np
b = a.numpy()

In [120]:
b

array([[0.        , 0.01025492, 0.9516023 ],
       [0.2855265 , 0.23241723, 0.9140916 ]], dtype=float32)

In [121]:
type(b)

numpy.ndarray

In [122]:
c=torch.from_numpy(b)

tensor([[0.0000, 0.0103, 0.9516],
        [0.2855, 0.2324, 0.9141]])

In [123]:
type(c)

torch.Tensor